import Head from 'next/head';
import React from 'react'
import NavBar from './navbar';


type Prop = {
	children: any
}

function Layout({ children }: Prop) {
	return (
		<div className="h-screen p-6">
			<Head>
				<title>My App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar />
			<div style={{ height: 'calc(100vh - 128px)' }}>{children}</div>
		</div >
	)
}

export default Layout;
