import type { NextPage } from 'next'
import Head from 'next/head'
import { useSelector } from 'react-redux';
import withSession from '../lib/withSession';
import { clearAuthenticated, isAuthenticatedSelector, setAuthenticated } from '../store/slices/authSlice';
import { RootState, wrapper } from '../store/store';

const Home: NextPage = () => {
  const isAuthenticated = useSelector((state: RootState) => isAuthenticatedSelector(state.auth));

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6 bg-white rounded">
        <h1>Welcome</h1>
        <p>{isAuthenticated ? 'Authen' : 'Nah'}</p>
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => withSession(async ({ req, res }: any) => {
  const user = req.session.get("user");

  if (user === undefined) {
    store.dispatch(clearAuthenticated());

    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  } else if (user) {
    store.dispatch(setAuthenticated({ isAuthenticated: true, userName: user.login }));

    return {
      props: { user: req.session.get("user") },
    };
  }
}));

export default Home
