import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6 bg-white rounded">
        <h1>Welcome</h1>
      </main>
    </div>
  )
}

// export const getServerSideProps: GetServerSideProps = async () => {
//   return {
//     redirect: {
//       destination: '/user',
//       permanent: false,
//     },
//   }
// }


export default Home
